import type { PromptTemplate, PromptVariable } from "@/types/llmchef/prompt-template";
import type { WorkflowTemplate, WorkflowStep } from "@/types/llmchef/workflow";

export type WorkflowPreviewContext = {
  workflow: WorkflowTemplate;
  initial_step: unknown;
  outputs: unknown[];
};

const SAMPLE_RAW_TRANSFORM_TEXT =
  "Sample AI response text that would be output by the initial step. This is raw, unstructured text that the transform step will process using JSONPath queries to extract specific data.";

const SAMPLE_RAW_STEP_TEXT = (stepName: string): string =>
  `Sample AI response from ${stepName}. This is the raw text output that would be generated by the AI model when processing this step. It contains unstructured information that the transform step will extract using JSONPath queries.`;

const DEFAULT_WORKFLOW: WorkflowTemplate = {
  id: "sample-workflow",
  name: "Sample Workflow",
  description: "A sample workflow for validation",
  triggerType: "custom",
  triggerPrompt: "Sample initial prompt",
  steps: [],
  createdAt: new Date(0).toISOString(),
  updatedAt: new Date(0).toISOString(),
};

const createSampleValueForVariable = (variable: PromptVariable): unknown => {
  switch (variable.type) {
    case "number":
      return 42;
    case "boolean":
      return true;
    case "array":
      return ["item1", "item2"];
    case "string":
    default:
      return `Sample ${variable.name}`;
  }
};

const findTemplateById = (
  templates: PromptTemplate[],
  templateId?: string,
): PromptTemplate | undefined => templates.find((template) => template.id === templateId);

const createStructuredStepOutput = (
  step: WorkflowStep,
  templates: PromptTemplate[],
): Record<string, unknown> => {
  const template = findTemplateById(templates, step.templateId);
  if (template?.variables?.length) {
    return template.variables.reduce<Record<string, unknown>>((accumulator, variable) => {
      accumulator[variable.name] = createSampleValueForVariable(variable);
      return accumulator;
    }, {});
  }

  return {
    result: `Sample output from ${step.name}`,
    step_type: step.type,
    step_name: step.name,
  };
};

const createStepOutput = (
  step: WorkflowStep,
  nextStep: WorkflowStep | undefined,
  templates: PromptTemplate[],
): unknown => {
  const nextStepIsTransform = nextStep?.type === "transform";

  if (step.type === "prompt" || step.type === "agent-task") {
    return nextStepIsTransform
      ? SAMPLE_RAW_STEP_TEXT(step.name)
      : createStructuredStepOutput(step, templates);
  }

  if (step.type === "transform") {
    return {
      transformed_data: "Sample transformed data",
      step_type: "transform",
      step_name: step.name,
    };
  }

  if (step.type === "human-in-the-loop") {
    return {
      human_input: "Sample human review result",
      approved: true,
      step_type: "human-in-the-loop",
      step_name: step.name,
    };
  }

  return {
    result: `Sample output from ${step.name}`,
    step_type: step.type,
    step_name: step.name,
  };
};

const createInitialStepData = (
  workflow: WorkflowTemplate | undefined,
  templates: PromptTemplate[],
): unknown => {
  if (!workflow) {
    return "Sample AI response text for validation purposes.";
  }

  const firstStep = workflow.steps[0];
  if (firstStep?.type === "transform") {
    return SAMPLE_RAW_TRANSFORM_TEXT;
  }

  if (workflow.triggerType === "template" && workflow.triggerRef) {
    const template = findTemplateById(templates, workflow.triggerRef);
    return {
      summary: `Sample output from template: ${template?.name || "Selected Template"}`,
      extracted_data: "Sample extracted information",
      status: "completed",
    };
  }

  if (workflow.triggerType === "task" && workflow.triggerRef) {
    const task = findTemplateById(templates, workflow.triggerRef);
    return {
      result: `Sample result from agent task: ${task?.name || "Selected Task"}`,
      recommendations: ["rec 1", "rec 2"],
      next_actions: "Sample next actions",
    };
  }

  return {
    analysis: "Sample analysis of the custom prompt",
    key_points: ["point 1", "point 2", "point 3"],
    confidence: 0.85,
  };
};

export const buildWorkflowPreviewContext = (
  workflow: WorkflowTemplate | undefined,
  stepIndex: number | undefined,
  templates: PromptTemplate[],
): WorkflowPreviewContext => {
  const resolvedWorkflow = workflow ?? DEFAULT_WORKFLOW;
  const initialStepData = createInitialStepData(workflow, templates);
  const outputs: unknown[] = [initialStepData];

  if (workflow && stepIndex !== undefined) {
    for (let index = 0; index < stepIndex; index += 1) {
      const step = workflow.steps[index];
      if (!step) continue;
      outputs[index + 1] = createStepOutput(step, workflow.steps[index + 1], templates);
    }
  } else {
    outputs[1] = {
      analysis: "Sample analysis result",
      confidence: 0.85,
      entities: ["entity1", "entity2"],
    };
    outputs[2] = {
      summary: "Sample summary from step 1",
      items: ["processed_item1", "processed_item2"],
      metadata: { source: "step1", timestamp: "2024-01-01T00:00:00Z" },
    };
  }

  return {
    workflow: resolvedWorkflow,
    initial_step: initialStepData,
    outputs,
  };
};
