import type { ControlModuleConstructor } from "@/types/llmchef/control";

export const loadAdvancedControlModules =
  async (): Promise<ControlModuleConstructor[]> => {
    const [
      { AgentControlModule },
      { AssistantSettingsModule },
      { DataSettingsModule },
      { GeneralSettingsModule },
      { GitSyncControlModule },
      { GitToolsModule },
      { ImageGenerationControlModule },
      { ImprovePromptControlModule },
      { ManualSyncSidebarControlModule },
      { McpToolsModule },
      { ModSettingsModule },
      { NetworkLedgerSettingsModule },
      { PromptLibraryControlModule },
      { ProviderSettingsModule },
      { RacePromptControlModule },
      { RaceResultExportControlModule },
      { RunnableBlocksSettingsModule },
      { ThemeSettingsControlModule },
      { UsageDashboardModule },
      { VfsToolsModule },
      { WebSearchControlModule },
      { WebSearchToolsModule },
      { WorkflowControlModule },
      { WorkflowDisplayModule },
      { WorkflowWebSearchControlModule },
    ] = await Promise.all([
      import("@/controls/modules/AgentControlModule"),
      import("@/controls/modules/AssistantSettingsModule"),
      import("@/controls/modules/DataSettingsModule"),
      import("@/controls/modules/GeneralSettingsModule"),
      import("@/controls/modules/GitSyncControlModule"),
      import("@/controls/modules/GitToolsModule"),
      import("@/controls/modules/ImageGenerationControlModule"),
      import("@/controls/modules/ImprovePromptControlModule"),
      import("@/controls/modules/ManualSyncSidebarControlModule"),
      import("@/controls/modules/McpToolsModule"),
      import("@/controls/modules/ModSettingsModule"),
      import("@/controls/modules/NetworkLedgerSettingsModule"),
      import("@/controls/modules/PromptLibraryControlModule"),
      import("@/controls/modules/ProviderSettingsModule"),
      import("@/controls/modules/RacePromptControlModule"),
      import("@/controls/modules/canvas/RaceResultExportControlModule"),
      import("@/controls/modules/RunnableBlocksSettingsModule"),
      import("@/controls/modules/ThemeSettingsControlModule"),
      import("@/controls/modules/UsageDashboardModule"),
      import("@/controls/modules/VfsToolsModule"),
      import("@/controls/modules/WebSearchControlModule"),
      import("@/controls/modules/WebSearchToolsModule"),
      import("@/controls/modules/WorkflowControlModule"),
      import("@/controls/modules/WorkflowDisplayModule"),
      import("@/controls/modules/WorkflowWebSearchControlModule"),
    ]);

    return [
      GeneralSettingsModule,
      NetworkLedgerSettingsModule,
      ThemeSettingsControlModule,
      ProviderSettingsModule,
      AssistantSettingsModule,
      RunnableBlocksSettingsModule,
      DataSettingsModule,
      ModSettingsModule,
      UsageDashboardModule,
      WebSearchControlModule,
      WorkflowWebSearchControlModule,
      ImageGenerationControlModule,
      RacePromptControlModule,
      ImprovePromptControlModule,
      PromptLibraryControlModule,
      AgentControlModule,
      WorkflowControlModule,
      WorkflowDisplayModule,
      GitSyncControlModule,
      ManualSyncSidebarControlModule,
      VfsToolsModule,
      GitToolsModule,
      WebSearchToolsModule,
      McpToolsModule,
      RaceResultExportControlModule,
    ];
  };
